services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lolsing-streak
    ports:
      - "5432:5432"