services:
  lolsing-streak:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    image: lolsing-streak:latest
    container_name: lolsing-streak
    ports:
      - "8080:8080"
    env_file:
      - .env