CREATE TABLE Account
(
    puuid    VARCHAR(255) NOT NULL,
    gameName VARCHAR(255),
    tagLine  VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (puuid)
);

CREATE TABLE Match
(
    matchId            VARCHAR(255) NOT NULL,
    gameCreation       BIGINT       NOT NULL,
    gameDuration       INTEGER      NOT NULL,
    gameStartTimestamp BIGINT       NOT NULL,
    gameEndTimestamp   BIGINT       NOT NULL,
    gameMode           VARCHAR(255),
    CONSTRAINT pk_match PRIMARY KEY (matchId)
);

CREATE TABLE Participant
(
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_id                         VARCHAR(255)                            NOT NULL,
    puuid                            VARCHAR(255),
    championName                     VARCHAR(255),
    riotIdGameName                   VARCHAR(255),
    riotIdTagline                    VARCHAR(255),
    role                             VARCHAR(255),
    kills                            INTEGER                                 NOT NULL,
    deaths                           INTEGER                                 NOT NULL,
    assists                          INTEGER                                 NOT NULL,
    win                              BOOLEAN                                 NOT NULL,
    takedowns                        INTEGER                                 NOT NULL,
    kda                              FLOAT                                   NOT NULL,
    killParticipation                FLOAT                                   NOT NULL,
    multikills                       INTEGER                                 NOT NULL,
    legendaryCount                   INTEGER                                 NOT NULL,
    damagePerMinute                  FLOAT                                   NOT NULL,
    teamDamagePercentage             FLOAT                                   NOT NULL,
    effectiveHealAndShielding        FLOAT                                   NOT NULL,
    highestChampionDamage            INTEGER                                 NOT NULL,
    baronTakedowns                   INTEGER                                 NOT NULL,
    dragonTakedowns                  INTEGER                                 NOT NULL,
    firstTurretKilled                INTEGER                                 NOT NULL,
    riftHeraldTakedowns              INTEGER                                 NOT NULL,
    turretTakedowns                  INTEGER                                 NOT NULL,
    visionScorePerMinute             FLOAT                                   NOT NULL,
    controlWardsPlaced               INTEGER                                 NOT NULL,
    survivedSingleDigitHpCount       INTEGER                                 NOT NULL,
    dodgeSkillShotsSmallWindow       INTEGER                                 NOT NULL,
    earlyLaningPhaseGoldExpAdvantage INTEGER                                 NOT NULL,
    goldPerMinute                    FLOAT                                   NOT NULL,
    mythicItemUsed                   INTEGER                                 NOT NULL,
    gameLength                       FLOAT                                   NOT NULL,
    playedChampSelectPosition        INTEGER                                 NOT NULL,
    legendaryItemUsed                INTEGER[],
    CONSTRAINT pk_participant PRIMARY KEY (id)
);

ALTER TABLE Participant
    ADD CONSTRAINT FK_PARTICIPANT_ON_MATCH
    FOREIGN KEY (match_id)
    REFERENCES Match (matchId)
    ON DELETE CASCADE;